{
  "Logging": {
    "IncludeScopes": false,
    "Debug": {
      "LogLevel": {
        "Default": "Debug",
        "Fortune_Teller_UI": "Debug",
        "Steeltoe": "Debug",
        "Pivotal": "Debug"
      }
    },
    "Console": {
      "LogLevel": {
        "Default": "Debug",
        "Fortune_Teller_UI": "Debug",
        "Steeltoe": "Debug",
        "Pivotal": "Debug"
      }
    }
  }
}